fix: always use kubernetes-cli version of kubectl
Docker installs kubectl to /Applications/Docker.app/Contents/Resources/bin/kubectl and links it to /usr/local/bin/kubectl.
But it's an older version than kubernetes-cli.

When running `setup upgrade` a newer version of Docker will overwrite kubernetes-cli. The next time `setup upgrade` runs and there's a newer version of kubernetes-cli it will show the error:

```
Linking /usr/local/Cellar/kubernetes-cli/1.23.4...
Error: Could not symlink bin/kubectl
Target /usr/local/bin/kubectl
already exists. You may want to remove it:
  rm '/usr/local/bin/kubectl'

To force the link and overwrite all conflicting files:
  brew link --overwrite kubernetes-cli

To list all files that would be deleted:
  brew link --overwrite --dry-run kubernetes-cli
```

This PR adds  `brew link --overwrite --dry-run kubernetes-cli` to the install script so we never have the Docker version of kubectl installed (and therefore don't get the error above) and always have the latest version of kubectl.

Ideally this would be possible in the Brewfile itself, see https://github.com/Homebrew/homebrew-bundle/issues/1062