chore: remove python@3.8 because it is EOL
fixes:

```
Installing python@3.8 formula. It is not currently installed.
Error: python@3.8 has been disabled because it is deprecated upstream! It was disabled on 2024-10-14.
Error: python@3.8 has been disabled because it is deprecated upstream! It was disabled on 2024-10-14.
Installing python@3.8 has failed!
```