fix: remove brew bundle --no-lock
because its been removed see https://github.com/Homebrew/homebrew-bundle/pull/1630

fixes:
```
Error: invalid option: --no-lock
```