fix(fnm): remove --resolve-engines
because directories that have a package.json but don't specific a
version will error with:

```
error: Can't find version in dotfiles. Please provide a version manually to the command.
```